# -*- coding: utf-8 -*-
"""Evidencia - 5 min

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vp3K8muu0TSiMaIEUz2QR_SHO1uDb9PT
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
from google.colab import files

# Upload Excel files
print("Please upload PLTR-5min.xlsx")
pltr_upload = files.upload()
pltr_filename = list(pltr_upload.keys())[0]
pltr_df = pd.read_excel(pltr_filename)

print("Please upload BSX-5min.xlsx")
bsx_upload = files.upload()
bsx_filename = list(bsx_upload.keys())[0]
bsx_df = pd.read_excel(bsx_filename)

print("Please upload AAPL-5min.xlsx")
aapl_upload = files.upload()
aapl_filename = list(aapl_upload.keys())[0]
aapl_df = pd.read_excel(aapl_filename)

# Print available columns
print("\nPLTR DataFrame columns:", list(pltr_df.columns))
print("BSX DataFrame columns:", list(bsx_df.columns))
print("AAPL DataFrame columns:", list(aapl_df.columns))

# Hardcode the close column name based on common financial data (modify if needed)
close_column = 'Close'  # Adjust this based on actual column name in your Excel files
print(f"Using column '{close_column}' for closing prices. If incorrect, please check the column names above.")

# Extract closing prices
try:
    pltr_close = pltr_df[close_column]
    bsx_close = bsx_df[close_column]
    aapl_close = aapl_df[close_column]
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and update the close_column variable")
    raise

# Clean data: Remove NaN and inf values
pltr_close = pltr_close.replace([np.inf, -np.inf], np.nan).dropna()
bsx_close = bsx_close.replace([np.inf, -np.inf], np.nan).dropna()
aapl_close = aapl_close.replace([np.inf, -np.inf], np.nan).dropna()

# Align series by minimum length
min_length = min(len(pltr_close), len(bsx_close), len(aapl_close))
pltr_close = pltr_close.iloc[:min_length]
bsx_close = bsx_close.iloc[:min_length]
aapl_close = aapl_close.iloc[:min_length]

# Check if data is non-empty
if len(pltr_close) == 0 or len(bsx_close) == 0 or len(aapl_close) == 0:
    raise ValueError("Error: One or more series is empty after cleaning NaN/inf values")

# Random Walk Test (Variance Ratio Test)
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diffs = series.diff().dropna()
    var_original = np.var(series)
    var_diff = np.var(diffs)
    ratio = var_original / (len(series) * var_diff)
    print(f"Variance Ratio: {ratio:.4f}")
    print("Interpretation:")
    if abs(ratio - 1) < 0.1:
        print(f"  - Variance ratio ≈ 1: {name} behaves like a random walk")
    else:
        print(f"  - Variance ratio ≠ 1: {name} may not be a pure random walk")

random_walk_test(pltr_close, "PLTR")
random_walk_test(bsx_close, "BSX")
random_walk_test(aapl_close, "AAPL")

# Unit Root Tests (ADF and KPSS)
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")
    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")
    # KPSS Test
    kpss_result = kpss(series, regression='c')
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")

unit_root_tests(pltr_close, "PLTR")
unit_root_tests(bsx_close, "BSX")
unit_root_tests(aapl_close, "AAPL")

# Difference the series
pltr_diff = pltr_close.diff().dropna()
bsx_diff = bsx_close.diff().dropna()
aapl_diff = aapl_close.diff().dropna()

# Test stationarity of differenced series
unit_root_tests(pltr_diff, "PLTR Differenced")
unit_root_tests(bsx_diff, "BSX Differenced")
unit_root_tests(aapl_diff, "AAPL Differenced")

# Function to fit and evaluate AR, ARMA, and ARIMA models
def fit_time_series_models(series, name, max_p=3, max_q=3):
    print(f"\nFitting Time Series Models for {name}:")

    # Store results for comparison
    models_results = []

    # Fit AR models (ARIMA with q=0, d=0)
    best_ar_aic = float('inf')
    best_ar_order = None
    for p in range(1, max_p + 1):
        try:
            model = ARIMA(series, order=(p, 0, 0))
            results = model.fit()
            models_results.append(('AR', (p, 0, 0), results.aic))
            if results.aic < best_ar_aic:
                best_ar_aic = results.aic
                best_ar_order = (p, 0, 0)
        except:
            continue

    # Fit ARMA models (ARIMA with p>0, q>0, d=0)
    best_arma_aic = float('inf')
    best_arma_order = None
    for p in range(1, max_p + 1):
        for q in range(1, max_q + 1):
            try:
                model = ARIMA(series, order=(p, 0, q))
                results = model.fit()
                models_results.append(('ARMA', (p, 0, q), results.aic))
                if results.aic < best_arma_aic:
                    best_arma_aic = results.aic
                    best_arma_order = (p, 0, q)
            except:
                continue

    # Fit ARIMA models (d=1 to account for differencing)
    best_arima_aic = float('inf')
    best_arima_order = None
    for p in range(max_p + 1):
        for q in range(max_q + 1):
            try:
                model = ARIMA(series, order=(p, 1, q))
                results = model.fit()
                models_results.append(('ARIMA', (p, 1, q), results.aic))
                if results.aic < best_arima_aic:
                    best_arima_aic = results.aic
                    best_arima_order = (p, 1, q)
            except:
                continue

    # Print model comparison
    print(f"\nModel Comparison for {name}:")
    print("Model Type | Order | AIC")
    print("-" * 30)
    for model_type, order, aic in models_results:
        print(f"{model_type:<10} | {order} | {aic:.2f}")

    # Select the best overall model
    best_model = min(models_results, key=lambda x: x[2])
    best_model_type, best_order, best_aic = best_model
    print(f"\nBest Model for {name}:")
    print(f"Type: {best_model_type}")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    if best_model_type == 'AR':
        print(f"  - AR({best_order[0]}): {best_order[0]} autoregressive term(s)")
    elif best_model_type == 'ARMA':
        print(f"  - ARMA({best_order[0]},{best_order[2]}): {best_order[0]} autoregressive term(s), {best_order[2]} moving average term(s)")
    elif best_model_type == 'ARIMA':
        print(f"  - ARIMA({best_order[0]},1,{best_order[2]}): {best_order[0]} autoregressive term(s), 1 differencing, {best_order[2]} moving average term(s)")

    return best_model_type, best_order

# Fit models for each series (use differenced series for AR and ARMA, original for ARIMA)
pltr_model_type, pltr_order = fit_time_series_models(pltr_diff, "PLTR")
bsx_model_type, bsx_order = fit_time_series_models(bsx_diff, "BSX")
aapl_model_type, aapl_order = fit_time_series_models(aapl_diff, "AAPL")

# Fit the best model for forecasting
def fit_best_model(series, model_type, order, name):
    if model_type in ['AR', 'ARMA']:
        model = ARIMA(series, order=order)
    else:  # ARIMA
        model = ARIMA(series, order=order)
    return model.fit()

pltr_model = fit_best_model(pltr_diff if pltr_model_type in ['AR', 'ARMA'] else pltr_close, pltr_model_type, pltr_order, "PLTR")
bsx_model = fit_best_model(bsx_diff if bsx_model_type in ['AR', 'ARMA'] else bsx_close, bsx_model_type, bsx_order, "BSX")
aapl_model = fit_best_model(aapl_diff if aapl_model_type in ['AR', 'ARMA'] else aapl_close, aapl_model_type, aapl_order, "AAPL")

# Cointegration Test
def cointegration_test(df):
    result = coint_johansen(df, det_order=0, k_ar_diff=1)
    print("\nJohansen Cointegration Test (PLTR, BSX, AAPL):")
    print(f"Trace statistic: {result.lr1}")
    print(f"Critical values (90%, 95%, 99%): {result.cvt}")
    print("Interpretation:")
    for i in range(len(result.lr1)):
        if result.lr1[i] > result.cvt[i, 1]:
            print(f"  - r = {i}: Cointegration exists at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
        else:
            print(f"  - r = {i}: No cointegration at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
    if result.lr1[0] > result.cvt[0, 1]:
        print("Conclusion: PLTR, BSX, and AAPL are cointegrated - they share a long-run equilibrium relationship")
    else:
        print("Conclusion: No evidence of cointegration among PLTR, BSX, and AAPL")

# Prepare data for cointegration
coint_df = pd.DataFrame({
    'PLTR': pltr_close,
    'BSX': bsx_close,
    'AAPL': aapl_close
}).dropna()
cointegration_test(coint_df)

# Forecast next 30 periods (30 * 5min = 150 minutes or 2.5 hours)
forecast_steps = 30
pltr_forecast = pltr_model.forecast(steps=forecast_steps)
bsx_forecast = bsx_model.forecast(steps=forecast_steps)
aapl_forecast = aapl_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(pltr_close) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot original series with forecasts
plt.figure(figsize=(12, 6))
plt.plot(pltr_close, label='PLTR Historical')
plt.plot(forecast_index, pltr_forecast, label='PLTR Forecast', color='red')
plt.plot(bsx_close, label='BSX Historical')
plt.plot(forecast_index, bsx_forecast, label='BSX Forecast', color='green')
plt.plot(aapl_close, label='AAPL Historical')
plt.plot(forecast_index, aapl_forecast, label='AAPL Forecast', color='purple')
plt.title('PLTR, BSX, and AAPL Closing Prices (5-min) with Forecasts')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals
def plot_forecast(model, series, name, steps=30, is_diff_series=False):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()
    forecast_index = range(len(series), len(series) + steps)
    plt.figure(figsize=(12, 6))
    plt.plot(series, label=f'{name} Historical {"(Differenced)" if is_diff_series else ""}')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                     conf_int.iloc[:, 0],
                     conf_int.iloc[:, 1],
                     color='pink',
                     alpha=0.3,
                     label='95% Confidence Interval')
    plt.title(f'{name} Price Forecast (5-min)')
    plt.legend()
    plt.show()
    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
plot_forecast(pltr_model, pltr_diff if pltr_model_type in ['AR', 'ARMA'] else pltr_close, "PLTR", is_diff_series=pltr_model_type in ['AR', 'ARMA'])
plot_forecast(bsx_model, bsx_diff if bsx_model_type in ['AR', 'ARMA'] else bsx_close, "BSX", is_diff_series=bsx_model_type in ['AR', 'ARMA'])
plot_forecast(aapl_model, aapl_diff if aapl_model_type in ['AR', 'ARMA'] else aapl_close, "AAPL", is_diff_series=aapl_model_type in ['AR', 'ARMA'])

# Print forecast values
print("\nPLTR Forecast Values (next 5 periods):")
print(pltr_forecast[:5])
print("\nBSX Forecast Values (next 5 periods):")
print(bsx_forecast[:5])
print("\nAAPL Forecast Values (next 5 periods):")
print(aapl_forecast[:5])